// Error code constants organized by category

export enum ErrorCodes {
  // Authentication errors
  INVALID_CREDENTIALS = 'AUTH_001',
  ACCOUNT_LOCKED = 'AUTH_002',
  TOKEN_EXPIRED = 'AUTH_003',
  TOKEN_INVALID = 'AUTH_004',
  UNAUTHORIZED = 'AUTH_005',
  FORBIDDEN = 'AUTH_006',

  // Validation errors
  VALIDATION_FAILED = 'VALIDATION_001',
  INVALID_INPUT = 'VALIDATION_002',
  MISSING_REQUIRED_FIELD = 'VALIDATION_003',

  // Security errors
  RATE_LIMIT_EXCEEDED = 'SECURITY_001',
  SUSPICIOUS_ACTIVITY = 'SECURITY_002',
  IP_BLOCKED = 'SECURITY_003',

  // Database errors
  DATABASE_CONNECTION_FAILED = 'DB_001',
  RECORD_NOT_FOUND = 'DB_002',
  DUPLICATE_ENTRY = 'DB_003',
  CONSTRAINT_VIOLATION = 'DB_004',

  // External service errors
  EXTERNAL_SERVICE_UNAVAILABLE = 'EXT_001',
  GRPC_CONNECTION_FAILED = 'EXT_002',
  KAFKA_PUBLISH_FAILED = 'EXT_003',
  REDIS_CONNECTION_FAILED = 'EXT_004',

  // WebSocket errors
  WEBSOCKET_CONNECTION_FAILED = 'WS_001',
  WEBSOCKET_AUTHENTICATION_FAILED = 'WS_002',
  WEBSOCKET_MESSAGE_INVALID = 'WS_003',

  // General errors
  INTERNAL_SERVER_ERROR = 'GEN_001',
  SERVICE_UNAVAILABLE = 'GEN_002',
  TIMEOUT = 'GEN_003',
  CONFIGURATION_ERROR = 'GEN_004',
}
