name: Build & Deploy Nexus BE
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  DEPLOY_DIR: /home/${{ secrets.EC2_USER }}/app/nexus-be
  REPO: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Save EC2 private key
        run: |
          echo "${{ secrets.EC2_KEY }}" | tr -d '\r' > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Test EC2 SSH connectivity
        run: |
          echo "Testing SSH connection to ${{ secrets.EC2_HOST }}..."
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem -p ${{ secrets.EC2_PORT || 22 }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo Connection successful"

      - name: Deploy & restart services on EC2
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT || 22 }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          export DEPLOY_DIR=/home/${{ secrets.EC2_USER }}/app/nexus-be
          echo "Ensuring deployment folder exists..."
          mkdir -p $DEPLOY_DIR

          echo "Navigating to deployment folder..."
          cd $DEPLOY_DIR

          if [ -d ".git" ]; then
            echo "Pulling latest changes from main branch..."
            git reset --hard
            git pull origin main
          else
            echo "Cloning repository..."
            git clone https://github.com/$REPO.git $DEPLOY_DIR
          fi

          echo "Installing dependencies..."
          pnpm install --no-frozen-lockfile

          echo "Building packages..."
          pnpm --filter './packages/*' run build

          echo "Building apps..."
          pnpm --filter './apps/*' run build

          echo "Restarting services..."
          cd $DEPLOY_DIR/apps
          for svc in gateway-svc trading-svc findata-svc notification-svc; do
            echo "Deploying $svc..."
            cd $DEPLOY_DIR/apps/$svc
            pm2 restart $svc || pm2 start dist/main.js --name $svc
          done

          pm2 save
          echo "Deployment completed successfully."
          EOF
