name: Build Nexus BE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js and pnpm
      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          package-manager: 'pnpm'
          check-latest: true

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4️⃣ Build all packages
      - name: Build packages
        run: pnpm --filter './packages/*' run build

      # 5️⃣ Build all apps
      - name: Build apps
        run: pnpm --filter './apps/*' run build

      # 6️⃣ Prepare artifacts folder
      - name: Archive dist folders
        run: |
          mkdir -p artifacts/packages
          mkdir -p artifacts/apps
          cp -R packages/*/dist artifacts/packages/
          cp -R apps/*/dist artifacts/apps/

      # 7️⃣ Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nexus-dist
          path: artifacts/
