name: Build Nexus BE
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          check-latest: true
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build packages
        run: pnpm --filter './packages/*' run build
      
      - name: Build apps
        run: pnpm --filter './apps/*' run build
      
      - name: Archive dist folders
        run: |
          mkdir -p artifacts/packages artifacts/apps
          find packages -name "dist" -type d -exec cp -R {} artifacts/packages/ \;
          find apps -name "dist" -type d -exec cp -R {} artifacts/apps/ \;
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nexus-dist
          path: artifacts/
