name: Build Nexus BE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm --filter './packages/*' run build

      - name: Build apps
        run: pnpm --filter './apps/*' run build

      - name: Archive dist folders
        run: |
          mkdir -p artifacts
          cp -R packages/*/dist artifacts/packages/
          cp -R apps/*/dist artifacts/apps/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nexus-dist
          path: artifacts/
