name: Build Nexus BE
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  DEPLOY_DIR: /home/${{ secrets.EC2_USER }}/app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          check-latest: true
      
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      
      - name: Build packages
        run: pnpm --filter './packages/*' run build
      
      - name: Build apps
        run: pnpm --filter './apps/*' run build
      
      - name: Archive dist folders
        run: |
          mkdir -p artifacts/packages
          mkdir -p artifacts/apps
          cp -R packages/*/dist artifacts/packages/
          cp -R apps/*/dist artifacts/apps/
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nexus-dist
          path: artifacts/

      - name: Save EC2 private key
        run: |
          echo "${{ secrets.EC2_KEY }}" | tr -d '\r' > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Test EC2 SSH connectivity
        run: |
          echo "Testing SSH connection to ${{ secrets.EC2_HOST }}..."
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem -p ${{ secrets.EC2_PORT || 22 }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo Connection successful"
    
      - name: Deploy to EC2 via SCP
        run: |
          mkdir -p $DEPLOY_DIR
          scp -i ec2_key.pem -o StrictHostKeyChecking=no -P ${{ secrets.EC2_PORT || 22 }} -r artifacts/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:$DEPLOY_DIR/

      - name: Restart server
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT || 22 }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          cd $DEPLOY_DIR/apps
          for svc in gateway-svc trading-svc findata-svc notification-svc; do
            cd $DEPLOY_DIR/apps/$svc
            npm install --production
            pm2 restart $svc || pm2 start dist/main.js --name $svc
          done
          pm2 save
