name: Deploy Nexus BE
on:
  workflow_dispatch:

env:
  DEPLOY_DIR: /home/${{ secrets.EC2_USER }}/app/nexus-be
  REPO: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Save EC2 private key
        run: |
          echo "${{ secrets.EC2_KEY }}" | tr -d '\r' > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Download artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Extract artifact
        run: |
          LATEST_TARBALL=$(ls -t artifacts-*.tar.gz | head -n1)
          tar -xzf $LATEST_TARBALL

      - name: Rsync artifacts to EC2
        run: |
          rsync -avz -e "ssh -i ec2_key.pem -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT || 22 }}" artifacts/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ env.DEPLOY_DIR }}/

      - name: Deploy & restart services on EC2
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT || 22 }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          set -e
          cd $DEPLOY_DIR
          # Add your deployment/restart commands here, e.g.:
          # pm2 restart all
          EOF
          
